services:
  - type: web
    name: voce-digital-backend
    runtime: python
    region: ohio
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SQLITE_MODE
        value: false
      - key: VOCE_DIGITAL_MASTER_KEY
        value: peNrjJ7xHXBM_FFJy9jTLNj_dGp2hmkoj-tXvIfw9lM=
      - key: SUPABASE_URL
        value: postgresql://postgres:Mjm1978*@db.mhdermskrgmqiiabjie.supabase.co:5432/postgres
      - key: SUPABASE_KEY
        value: Mjm1978*
